"""Git管理器 - 检查状态，提交代码"""

from typing import Optional

from utils.logger import get_logger
from utils.subprocess import run_command

logger = get_logger()


class GitManager:
    """Git管理器"""

    def __init__(self, working_dir: str = None, auto_commit: bool = True):
        self.working_dir = working_dir
        self.auto_commit = auto_commit

    def is_git_repo(self) -> bool:
        """检查是否是git仓库
        注意：git status会向上查找父目录的.git，所以必须检查是否存在.git目录
        只有当前工作目录下真的存在.git目录才认为是Git仓库
        """
        import os
        if self.working_dir is None:
            return False
        # 直接检查是否存在.git目录在当前工作目录
        git_dir = os.path.join(self.working_dir, '.git')
        return os.path.exists(git_dir)

    def init_repo(self) -> bool:
        """初始化git仓库"""
        import os

        from utils.file_utils import read_file, write_file

        logger.info("正在目标目录初始化Git仓库")

        # 检查是否已有 .gitignore
        gitignore_path = os.path.join(self.working_dir, '.gitignore')
        if not os.path.exists(gitignore_path):
            # 写入标准 .gitignore
            template = read_file(os.path.join(os.path.dirname(__file__), '../utils/templates/gitignore'))
            if template:
                write_file(gitignore_path, template)

        returncode, _, _ = run_command("git init", cwd=self.working_dir)
        if returncode != 0:
            logger.error("git init 失败")
            return False

        # 添加所有文件
        returncode, _, _ = run_command("git add .", cwd=self.working_dir)
        # 提交初始commit
        returncode, _, _ = run_command("git commit -m \"Initial commit: auto-generated by auto-coding\"", cwd=self.working_dir)

        logger.info("Git仓库初始化成功")
        return True

    def get_current_branch(self) -> Optional[str]:
        """获取当前分支"""
        returncode, stdout, _ = run_command("git branch --show-current", cwd=self.working_dir)
        if returncode == 0:
            return stdout.strip() or None
        return None

    def create_branch(self, branch_name: str) -> bool:
        """创建并切换到新分支"""
        if not self.is_git_repo():
            logger.warning("不是Git仓库，跳过分支创建")
            return False

        # 检查分支是否已存在
        returncode, _, _ = run_command(f"git show-ref --verify --quiet refs/heads/{branch_name}", cwd=self.working_dir)
        if returncode == 0:
            # 分支已存在，直接切换
            logger.info(f"分支 {branch_name} 已存在，切换到它")
            returncode, _, _ = run_command(f"git checkout {branch_name}", cwd=self.working_dir)
            return returncode == 0
        else:
            # 创建新分支
            logger.info(f"创建新分支: {branch_name}")
            returncode, _, _ = run_command(f"git checkout -b {branch_name}", cwd=self.working_dir)
            return returncode == 0

    def has_changes(self) -> bool:
        """检查是否有未提交的变更"""
        returncode, stdout, _ = run_command("git status --porcelain", cwd=self.working_dir)
        if returncode != 0:
            return False
        return bool(stdout.strip())

    def commit(self, story_id: str, story_title: str) -> Optional[str]:
        """提交所有变更"""
        if not self.auto_commit:
            logger.info("自动提交已禁用，跳过提交")
            return None

        if not self.is_git_repo():
            logger.warning("不是Git仓库，跳过提交")
            return None

        if not self.has_changes():
            logger.info("没有变更需要提交")
            return None

        commit_msg = f"[{story_id}] {story_title}"
        logger.info(f"正在提交变更: {commit_msg}")

        returncode, stdout, stderr = run_command("git add .", cwd=self.working_dir)
        if returncode != 0:
            error_msg = stderr or stdout
            logger.error(f"git add 失败: {error_msg}")
            return None

        returncode, stdout, stderr = run_command(f"git commit -m \"{commit_msg}\"", cwd=self.working_dir)
        if returncode != 0:
            error_msg = stderr or stdout
            logger.error(f"git commit 失败: {error_msg}")
            return None

        # 获取commit hash
        returncode, stdout, _ = run_command("git rev-parse HEAD", cwd=self.working_dir)
        if returncode == 0:
            commit_hash = stdout.strip()
            logger.info(f"提交成功: {commit_hash}")
            return commit_hash

        return None
